version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - app:/app

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - app:/app
      - data:/app/data

  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  app:
  data:
  mongodb:
