version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: personal-inventory
    ports:
      - 8080:80
    volumes:
      - data:/var/www/app/data

  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  data:
  mongodb: