index:
    path: /
    controller: App\Controller\Home::index

inventory_list:
    path: /inventory
    controller: App\Controller\Inventory::listItems
inventory_list_by_tag:
    path: /inventory/tags/{category}/{tag}
    controller: App\Controller\Inventory::listItems
inventory_add:
    path: /inventory/add
    controller: App\Controller\Inventory::editItem
inventory_get:
    path: /inventory/{id}
    controller: App\Controller\Inventory::getItem
inventory_edit:
    path: /inventory/{id}/edit
    controller: App\Controller\Inventory::editItem
inventory_image:
    path: /inventory/{id}/images/{filename}
    controller: App\Controller\Inventory::image
inventory_file:
    path: /inventory/{id}/files/{filename}
    controller: App\Controller\Inventory::itemfile

tag_list:
    path: /tags/{category}
    controller: App\Controller\Tag::listTags
